version: '3.8'

services:

  app:
    build: .
    container_name: actix_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - RUST_LOG=debug
    volumes:
      - .:/app

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: joaoprado
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rust:
    image: rust:latest
    container_name: rust_dev
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "cargo install diesel_cli --no-default-features --features postgres && diesel migration run"
    network_mode: "host"

volumes:
  pgdata:
